package uk.gov.hmcts.reform.iacasedocumentsapi.domain.entities.ccd;

import com.fasterxml.jackson.annotation.JsonEnumDefaultValue;
import com.fasterxml.jackson.annotation.JsonValue;

public enum NationalityGovUk {
    AF("Afghanistan"),
    AX("Aland Islands"),
    AL("Albania"),
    DZ("Algeria"),
    AD("Andorra"),
    AO("Angola"),
    AI("Anguilla"),
    AG("Antigua / Barbuda"),
    AR("Argentina"),
    AM("Armenia"),
    AW("Aruba"),
    AC("Ascension Island"),
    AU("Australia"),
    AT("Austria"),
    AZ("Azerbaijan"),
    BS("Bahamas"),
    BH("Bahrain"),
    BD("Bangladesh"),
    BB("Barbados"),
    BY("Belarus"),
    BE("Belgium"),
    BZ("Belize"),
    BJ("Benin"),
    BM("Bermuda"),
    BT("Bhutan"),
    BO("Bolivia"),
    BQ("Bonaire"),
    BA("Bosnia and Herzegovina"),
    BW("Botswana"),
    BR("Brazil"),
    IO("British Indian Ocean Territory"),
    VG("British Virgin Islands"),
    BN("Brunei Darussalam"),
    BG("Bulgaria"),
    BF("Burkina Faso"),
    BI("Burundi"),
    KH("Cambodia"),
    CM("Cameroon"),
    CA("Canada"),
    IC("Canary Islands"),
    CV("Cape Verde"),
    KY("Cayman Islands"),
    CF("Central African Republic"),
    EA("Ceuta"),
    TD("Chad"),
    CL("Chile"),
    CN("China"),
    CX("Christmas Island"),
    CO("Colombia"),
    KM("Comoros"),
    CG("Congo (Brazzaville)"),
    CD("Congo"),
    CK("Cook Islands"),
    CR("Costa Rica"),
    HR("Croatia"),
    CU("Cuba"),
    CW("Curacao"),
    CY("Cyprus"),
    CZ("Czech Republic"),
    DK("Denmark"),
    DJ("Djibouti"),
    DM("Dominica"),
    DO("Dominican Republic"),
    EC("Ecuador"),
    EG("Egypt"),
    SV("El Salvador"),
    GQ("Equatorial Guinea"),
    ER("Eritrea"),
    EE("Estonia"),
    SZ("Eswatini"),
    ET("Ethiopia"),
    FK("Falkland Islands"),
    FO("Faroe Islands"),
    FJ("Fiji"),
    FI("Finland"),
    FR("France"),
    GF("French Guiana"),
    PF("French Polynesia"),
    TF("French Southern Territories"),
    GA("Gabon"),
    GM("Gambia"),
    GE("Georgia"),
    DE("Germany"),
    GH("Ghana"),
    GI("Gibraltar"),
    GR("Greece"),
    GL("Greenland"),
    GD("Grenada"),
    GP("Guadeloupe"),
    GT("Guatemala"),
    GN("Guinea"),
    GW("Guinea-Bissau"),
    GY("Guyana"),
    HT("Haiti"),
    HN("Honduras"),
    HK("Hong Kong"),
    HU("Hungary"),
    IS("Iceland"),
    IN("India"),
    ID("Indonesia"),
    IR("Iran, Islamic Republic of"),
    IQ("Iraq"),
    IE("Ireland"),
    IL("Israel"),
    IT("Italy"),
    CI("Ivory Coast (Cote D'Ivoire"),
    JM("Jamaica"),
    JP("Japan"),
    JO("Jordan"),
    KZ("Kazakhstan"),
    KE("Kenya"),
    KI("Kiribati"),
    KR("Korea, Republic of"),
    KO("Kosovo"),
    KW("Kuwait"),
    KG("Kyrgyzstan"),
    LA("Laos"),
    LV("Latvia"),
    LB("Lebanon"),
    LS("Lesotho"),
    LR("Liberia"),
    LY("Libya"),
    LI("Liechtenstein"),
    LT("Lithuania"),
    LU("Luxembourg"),
    MO("Macao"),
    MK("Macedonia"),
    MG("Madagascar"),
    YT("Mahore (also known as Mayotte"),
    MW("Malawi"),
    MY("Malaysia"),
    MV("Maldives"),
    ML("Mali"),
    MT("Malta"),
    MQ("Martinique"),
    MR("Mauritania"),
    MU("Mauritius"),
    MX("Mexico"),
    MD("Moldova"),
    MN("Mongolia"),
    ME("Montenegro"),
    MS("Montserrat"),
    MA("Morocco"),
    MZ("Mozambique"),
    MM("Myanmar"),
    NA("Namibia"),
    NR("Nauru Islands"),
    NP("Nepal"),
    NL("Netherlands"),
    NC("New Caledonia"),
    NZ("New Zealand"),
    NI("Nicaragua"),
    NE("Niger Republic"),
    NG("Nigeria"),
    NU("Niue Islands"),
    KP("North Korea (People's Democratic Republic of)"),
    NO("Norway"),
    OM("Oman"),
    PK("Pakistan"),
    PW("Palau (known also as Belau)"),
    PA("Panama"),
    PG("Papua New Guinea"),
    PY("Paraguay"),
    PE("Peru"),
    PH("Philippines"),
    PN("Pitcairn Islands"),
    PL("Poland"),
    PT("Portugal"),
    PR("Puerto Rico"),
    QA("Qatar"),
    RE("Reunion Islands"),
    RO("Romania"),
    RU("Russian Federation"),
    RW("Rwanda"),
    LC("Saint Lucia"),
    SM("San Marino"),
    ST("Sao Tome & Principe"),
    SA("Saudi Arabia"),
    SN("Senegal"),
    RS("Serbia"),
    SC("Seychelles"),
    SL("Sierra Leone"),
    SG("Singapore"),
    SK("Slovakia"),
    SI("Slovenia"),
    SB("Solomon Islands"),
    ZA("South Africa"),
    SS("South Sudan"),
    ES("Spain"),
    LK("Sri Lanka"),
    SH("St Helena"),
    KN("St Kitts & Nevis"),
    MF("St Marteen"),
    VC("St Vincent & The Grenadines"),
    SD("Sudan"),
    SR("Suriname"),
    SE("Sweden"),
    CH("Switzerland"),
    SY("Syrian Arab Republic (Syria)"),
    TW("Taiwan"),
    TJ("Tajikistan"),
    TZ("Tanzania *, United Republic of"),
    TH("Thailand"),
    TL("Timor-Leste"),
    TG("Togo"),
    TK("Tokelau Islands"),
    TO("Tonga"),
    TT("Trinidad & Tobago"),
    TN("Tunisia"),
    TR("Turkey"),
    TM("Turkmenistan"),
    TC("Turks & Caicos Islands"),
    TV("Tuvalu"),
    UG("Uganda"),
    UA("Ukraine"),
    AE("United Arab Emirates"),
    GB("United Kingdom"),
    US("United States of America"),
    UY("Uruguay"),
    UZ("Uzbekistan"),
    VU("Vanuatu"),
    VA("Vatican City State"),
    VE("Venezuela"),
    VN("Viet Nam"),
    WF("Wallis & Futuna Islands"),
    EH("Western Sahara"),
    WS("Western Samoa"),
    YE("Yemen"),
    ZM("Zambia"),
    ZW("Zimbabwe"),

    @JsonEnumDefaultValue
    UNKNOWN("unknown");

    @JsonValue
    private final String id;

    NationalityGovUk(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return id;
    }

}
