docmosis.accessKey: unused
docmosis.endpoint: unused

security:
  authorisedServices:
    - "ia"

idam:
  s2s-authorised:
    services: ia

spring:
  data:
    redis:
      url: "redis://SOME_KEY@hostname.redis.cache.windows.net:6380?tls=true"
      secret: "something"
      encryption:
        key: "6YN2mGkOiEFMPzg/GCFdujQD9aXZN5oSd5LVwc9hX+Q="
      ssl:
        enabled: true